config/routes.rb
HelloWorld::Application.routes.draw do
  get "say/hello"

  get "say/goodbye"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
    @time = Time.now.end_of_week
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>Rails is fun!</p>
<br /><br />
Say <a href="/say/hello">hello</a> 
<br /><br />
End of week: <%= @time %>
<br /><br />
Or <%= link_to("hello", say_hello_path) %>

app/views/say/hello.html.erb
<p>Hello, World!</p>

<p>
  This is the time:  <%= @time %>
  <br /><br />
  Say <a href="/say/goodbye">goodbye</a>
  <br /><br />
  Or <%= link_to("goodbye", say_goodbye_path) %>
  <br /> <br />
  
  <!-- This file name thing could be useful for pulling back a list of
  images or something from a directory, keep it in mind I guess -->
  <%for file in @files%>
    file name is: <%= file %>
    <br />
  <% end %>
    
    <br /><br />
    
    I wanted to add this new text to my branch but won't be in the master.
  
</p>